## 1. Import Necessary Libraries

In [1]:
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_breast_cancer

from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score

## 2. Import Data

In [5]:
breast_cancer_data = load_breast_cancer()
breast_cancer_data_df = pd.DataFrame(breast_cancer_data.data,columns = breast_cancer_data.feature_names)
breast_cancer_data_df["Target"] = breast_cancer_data.target
breast_cancer_data_df

     mean radius  mean texture  mean perimeter  ...  worst symmetry  worst fractal dimension  Target
0          17.99         10.38          122.80  ...          0.4601                  0.11890       0
1          20.57         17.77          132.90  ...          0.2750                  0.08902       0
2          19.69         21.25          130.00  ...          0.3613                  0.08758       0
3          11.42         20.38           77.58  ...          0.6638                  0.17300       0
4          20.29         14.34          135.10  ...          0.2364                  0.07678       0
..           ...           ...             ...  ...             ...                      ...     ...
564        21.56         22.39          142.00  ...          0.2060                  0.07115       0
565        20.13         28.25          131.20  ...          0.2572                  0.06637       0
566        16.60         28.08          108.30  ...          0.2218                  0.07820       0
567        20.60         29.33          140.10  ...          0.4087                  0.12400       0
568         7.76         24.54           47.92  ...          0.2871                  0.07039       1

[569 rows x 31 columns]

## 3. Data Understanding

In [6]:
breast_cancer_data_df.isna().sum()

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
Target                     0
dtype: int64

In [7]:
breast_cancer_data_df.dtypes

mean radius                float64
mean texture               float64
mean perimeter             float64
mean area                  float64
mean smoothness            float64
mean compactness           float64
mean concavity             float64
mean concave points        float64
mean symmetry              float64
mean fractal dimension     float64
radius error               float64
texture error              float64
perimeter error            float64
area error                 float64
smoothness error           float64
compactness error          float64
concavity error            float64
concave points error       float64
symmetry error             float64
fractal dimension error    float64
worst radius               float64
worst texture              float64
worst perimeter            float64
worst area                 float64
worst smoothness           float64
worst compactness          float64
worst concavity            float64
worst concave points       float64
worst symmetry             float64
worst fractal dimension    float64
Target                       int64
dtype: object

## 4. Data Preparation

In [10]:
X = breast_cancer_data_df.drop("Target",axis=1)

In [12]:
std_scaler = StandardScaler()
scaled_X = pd.DataFrame(std_scaler.fit_transform(X))
scaled_X

           0         1         2         3         4   ...        25        26        27        28        29
0    1.097064 -2.073335  1.269934  0.984375  1.568466  ...  2.616665  2.109526  2.296076  2.750622  1.937015
1    1.829821 -0.353632  1.685955  1.908708 -0.826962  ... -0.430444 -0.146749  1.087084 -0.243890  0.281190
2    1.579888  0.456187  1.566503  1.558884  0.942210  ...  1.082932  0.854974  1.955000  1.152255  0.201391
3   -0.768909  0.253732 -0.592687 -0.764464  3.283553  ...  3.893397  1.989588  2.175786  6.046041  4.935010
4    1.750297 -1.151816  1.776573  1.826229  0.280372  ... -0.313395  0.613179  0.729259 -0.868353 -0.397100
..        ...       ...       ...       ...       ...  ...       ...       ...       ...       ...       ...
564  2.110995  0.721473  2.060786  2.343856  1.041842  ... -0.273318  0.664512  1.629151 -1.360158 -0.709091
565  1.704854  2.085134  1.615931  1.723842  0.102458  ... -0.394820  0.236573  0.733827 -0.531855 -0.973978
566  0.702284  2.045574  0.672676  0.577953 -0.840484  ...  0.350735  0.326767  0.414069 -1.104549 -0.318409
567  1.838341  2.336457  1.982524  1.735218  1.525767  ...  3.904848  3.197605  2.289985  1.919083  2.219635
568 -1.808401  1.221792 -1.814389 -1.347789 -3.112085  ... -1.207552 -1.305831 -1.745063 -0.048138 -0.751207

[569 rows x 30 columns]

In [13]:
y = breast_cancer_data_df.Target

## 5. Model Building

In [16]:
from sklearn.ensemble import GradientBoostingClassifier

In [33]:
gradient_boosting_classifier = GradientBoostingClassifier(n_estimators=50, max_depth=3,)

In [34]:
X_train,X_test,y_train,y_test = train_test_split(scaled_X,y,test_size=0.20,random_state=123,shuffle=True,stratify=y)

In [27]:
X_train.shape,y_train.shape

((455, 30), (455,))

In [28]:
X_test.shape,y_test.shape

((114, 30), (114,))

## 6. Model Training

In [56]:
start_time = datetime.now()
gradient_boosting_classifier.fit(X_train,y_train)
end_time = datetime.now()

print("Time Taken to Train the Algorithm:", end_time -  start_time)

Time Taken to Train the Algorithm: 0:00:00.349862

### 7. Model Testing || 8. Model Evaluation

#### Training Data

In [36]:
y_pred_train = gradient_boosting_classifier.predict(X_train)
print("Confusion Matrix:\n", confusion_matrix(y_train,y_pred_train))
print("Accuracy Score:"  ,accuracy_score(y_train,y_pred_train))
print("Precision Score:" ,precision_score(y_train,y_pred_train))
print("Recall Score:", recall_score(y_train,y_pred_train))

Confusion Matrix:
 [[170   0]
 [  0 285]]
Accuracy Score: 1.0
Precision Score: 1.0
Recall Score: 1.0

#### Test Data

In [37]:
y_pred_test = gradient_boosting_classifier.predict(X_test)
print("Confusion Matrix:\n", confusion_matrix(y_test,y_pred_test))
print("Accuracy Score:"  ,accuracy_score(y_test,y_pred_test))
print("Precision Score:" ,precision_score(y_test,y_pred_test))
print("Recall Score:", recall_score(y_test,y_pred_test))

Confusion Matrix:
 [[40  2]
 [ 3 69]]
Accuracy Score: 0.956140350877193
Precision Score: 0.971830985915493
Recall Score: 0.9583333333333334

### Extreme Gradient Boosting Machines?

In [55]:
from datetime import datetime

In [38]:
!pip install xgboost

Collecting xgboost
  Downloading xgboost-3.2.0-py3-none-win_amd64.whl (101.7 MB)
     ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
     ---------------------------------------- 0.1/101.7 MB 2.6 MB/s eta 0:00:39
     ---------------------------------------- 0.5/101.7 MB 6.6 MB/s eta 0:00:16
      -------------------------------------- 1.7/101.7 MB 13.4 MB/s eta 0:00:08
      -------------------------------------- 1.8/101.7 MB 11.6 MB/s eta 0:00:09
      -------------------------------------- 2.1/101.7 MB 10.3 MB/s eta 0:00:10
      --------------------------------------- 2.5/101.7 MB 9.4 MB/s eta 0:00:11
     - ------------------------------------- 3.3/101.7 MB 10.6 MB/s eta 0:00:10
     - ------------------------------------- 4.5/101.7 MB 12.6 MB/s eta 0:00:08
     -- ------------------------------------ 5.4/101.7 MB 14.5 MB/s eta 0:00:07
     --- ----------------------------------- 7.9/101.7 MB 17.5 MB/s eta 0:00:06
     --- ----------------------------------- 9.6/101.7 MB 19.1 MB/s eta 0:00:05
     ---- --------------------------------- 11.1/101.7 MB 22.6 MB/s eta 0:00:05
     ---- --------------------------------- 12.7/101.7 MB 31.2 MB/s eta 0:00:03
     ----- -------------------------------- 14.1/101.7 MB 36.4 MB/s eta 0:00:03
     ----- -------------------------------- 15.7/101.7 MB 36.3 MB/s eta 0:00:03
     ------ ------------------------------- 17.4/101.7 MB 34.4 MB/s eta 0:00:03
     ------- ------------------------------ 18.8/101.7 MB 32.8 MB/s eta 0:00:03
     ------- ------------------------------ 20.2/101.7 MB 32.7 MB/s eta 0:00:03
     -------- ----------------------------- 22.0/101.7 MB 34.4 MB/s eta 0:00:03
     -------- ----------------------------- 23.5/101.7 MB 34.6 MB/s eta 0:00:03
     --------- ---------------------------- 25.1/101.7 MB 34.4 MB/s eta 0:00:03
     ---------- --------------------------- 26.9/101.7 MB 34.4 MB/s eta 0:00:03
     ---------- --------------------------- 28.5/101.7 MB 34.4 MB/s eta 0:00:03
     ----------- -------------------------- 30.0/101.7 MB 34.4 MB/s eta 0:00:03
     ----------- -------------------------- 31.3/101.7 MB 34.4 MB/s eta 0:00:03
     ------------ ------------------------- 32.6/101.7 MB 32.7 MB/s eta 0:00:03
     ------------ ------------------------- 33.6/101.7 MB 31.1 MB/s eta 0:00:03
     ------------- ------------------------ 34.9/101.7 MB 31.2 MB/s eta 0:00:03
     ------------- ------------------------ 36.2/101.7 MB 29.8 MB/s eta 0:00:03
     -------------- ----------------------- 37.5/101.7 MB 28.5 MB/s eta 0:00:03
     -------------- ----------------------- 38.7/101.7 MB 27.3 MB/s eta 0:00:03
     -------------- ----------------------- 39.9/101.7 MB 26.2 MB/s eta 0:00:03
     --------------- ---------------------- 41.2/101.7 MB 26.2 MB/s eta 0:00:03
     --------------- ---------------------- 42.4/101.7 MB 26.2 MB/s eta 0:00:03
     ---------------- --------------------- 43.6/101.7 MB 26.2 MB/s eta 0:00:03
     ---------------- --------------------- 44.9/101.7 MB 26.2 MB/s eta 0:00:03
     ----------------- -------------------- 46.2/101.7 MB 26.2 MB/s eta 0:00:03
     ----------------- -------------------- 47.5/101.7 MB 27.3 MB/s eta 0:00:02
     ------------------ ------------------- 48.8/101.7 MB 28.5 MB/s eta 0:00:02
     ------------------ ------------------- 50.1/101.7 MB 28.5 MB/s eta 0:00:02
     ------------------- ------------------ 51.4/101.7 MB 28.5 MB/s eta 0:00:02
     ------------------- ------------------ 52.5/101.7 MB 28.5 MB/s eta 0:00:02
     -------------------- ----------------- 53.8/101.7 MB 28.5 MB/s eta 0:00:02
     -------------------- ----------------- 55.2/101.7 MB 28.4 MB/s eta 0:00:02
     --------------------- ---------------- 56.4/101.7 MB 28.4 MB/s eta 0:00:02
     --------------------- ---------------- 57.7/101.7 MB 27.3 MB/s eta 0:00:02
     ---------------------- --------------- 59.2/101.7 MB 28.5 MB/s eta 0:00:02
     ---------------------- --------------- 60.3/101.7 MB 27.3 MB/s eta 0:00:02
     ----------------------- -------------- 61.7/101.7 MB 28.5 MB/s eta 0:00:02
     ----------------------- -------------- 62.9/101.7 MB 28.5 MB/s eta 0:00:02
     ----------------------- -------------- 64.1/101.7 MB 27.3 MB/s eta 0:00:02
     ------------------------ ------------- 65.3/101.7 MB 27.3 MB/s eta 0:00:02
     ------------------------ ------------- 66.7/101.7 MB 27.3 MB/s eta 0:00:02
     ------------------------- ------------ 68.1/101.7 MB 27.3 MB/s eta 0:00:02
     ------------------------- ------------ 69.2/101.7 MB 28.4 MB/s eta 0:00:02
     -------------------------- ----------- 70.6/101.7 MB 27.3 MB/s eta 0:00:02
     -------------------------- ----------- 71.9/101.7 MB 27.3 MB/s eta 0:00:02
     --------------------------- ---------- 73.3/101.7 MB 27.3 MB/s eta 0:00:02
     --------------------------- ---------- 74.8/101.7 MB 28.5 MB/s eta 0:00:01
     ---------------------------- --------- 76.0/101.7 MB 28.4 MB/s eta 0:00:01
     ---------------------------- --------- 77.3/101.7 MB 27.3 MB/s eta 0:00:01
     ----------------------------- -------- 78.5/101.7 MB 27.3 MB/s eta 0:00:01
     ----------------------------- -------- 79.9/101.7 MB 28.5 MB/s eta 0:00:01
     ------------------------------ ------- 81.3/101.7 MB 29.7 MB/s eta 0:00:01
     ------------------------------ ------- 82.6/101.7 MB 29.7 MB/s eta 0:00:01
     ------------------------------- ------ 84.0/101.7 MB 29.8 MB/s eta 0:00:01
     ------------------------------- ------ 85.0/101.7 MB 28.5 MB/s eta 0:00:01
     -------------------------------- ----- 86.5/101.7 MB 29.7 MB/s eta 0:00:01
     -------------------------------- ----- 87.9/101.7 MB 29.7 MB/s eta 0:00:01
     --------------------------------- ---- 89.3/101.7 MB 29.7 MB/s eta 0:00:01
     --------------------------------- ---- 90.6/101.7 MB 29.7 MB/s eta 0:00:01
     ---------------------------------- --- 91.9/101.7 MB 29.7 MB/s eta 0:00:01
     ---------------------------------- --- 93.3/101.7 MB 28.4 MB/s eta 0:00:01
     ----------------------------------- -- 94.8/101.7 MB 29.8 MB/s eta 0:00:01
     ----------------------------------- -- 96.2/101.7 MB 29.8 MB/s eta 0:00:01
     ------------------------------------ - 97.4/101.7 MB 29.7 MB/s eta 0:00:01
     ------------------------------------ - 98.9/101.7 MB 29.7 MB/s eta 0:00:01
     ------------------------------------  100.3/101.7 MB 29.7 MB/s eta 0:00:01
     ------------------------------------  101.5/101.7 MB 29.7 MB/s eta 0:00:01
     ------------------------------------  101.7/101.7 MB 28.5 MB/s eta 0:00:01
     ------------------------------------  101.7/101.7 MB 28.5 MB/s eta 0:00:01
     ------------------------------------  101.7/101.7 MB 28.5 MB/s eta 0:00:01
     ------------------------------------  101.7/101.7 MB 28.5 MB/s eta 0:00:01
     ------------------------------------  101.7/101.7 MB 28.5 MB/s eta 0:00:01
     ------------------------------------  101.7/101.7 MB 28.5 MB/s eta 0:00:01
     ------------------------------------- 101.7/101.7 MB 15.2 MB/s eta 0:00:00
Requirement already satisfied: numpy in c:\users\john gabriel\appdata\local\programs\python\python310\lib\site-packages (from xgboost) (2.2.6)
Requirement already satisfied: scipy in c:\users\john gabriel\appdata\local\programs\python\python310\lib\site-packages (from xgboost) (1.15.3)
Installing collected packages: xgboost
Successfully installed xgboost-3.2.0

[notice] A new release of pip is available: 23.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [39]:
import xgboost as xgb

In [58]:
start_time = datetime.now()
xgb_classifier = xgb.XGBClassifier(max_depth = 3,n_estimators = 40,learning_rate = 0.008,gamma = 1.9, )
end_time = datetime.now()
print("Time Taken to Train the Algorithm:", end_time -  start_time)

Time Taken to Train the Algorithm: 0:00:00

In [52]:
xgb_classifier.fit(X_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=1.9, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.008, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=3,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=40,
              n_jobs=None, num_parallel_tree=None, ...)

In [53]:
y_pred_train = xgb_classifier.predict(X_train)
print("Confusion Matrix:\n", confusion_matrix(y_train,y_pred_train))
print("Accuracy Score:"  ,accuracy_score(y_train,y_pred_train))
print("Precision Score:" ,precision_score(y_train,y_pred_train))
print("Recall Score:", recall_score(y_train,y_pred_train))

Confusion Matrix:
 [[138  32]
 [  0 285]]
Accuracy Score: 0.9296703296703297
Precision Score: 0.8990536277602523
Recall Score: 1.0

In [54]:
y_pred_test = xgb_classifier.predict(X_test)
print("Confusion Matrix:\n", confusion_matrix(y_test,y_pred_test))
print("Accuracy Score:"  ,accuracy_score(y_test,y_pred_test))
print("Precision Score:" ,precision_score(y_test,y_pred_test))
print("Recall Score:", recall_score(y_test,y_pred_test))

Confusion Matrix:
 [[37  5]
 [ 0 72]]
Accuracy Score: 0.956140350877193
Precision Score: 0.935064935064935
Recall Score: 1.0

## The END!