# 1. Top 8 powerful functions n python for deeper data analysis
###### 1. Groupby
##### 2. Pivot table
##### 3. Aggregate
##### 4. Cross_tab
##### 5. concat
##### 6. apply
##### 7. lambda
##### 8. del(Keyword)

In [1]:
import pandas as pd

In [2]:
insurance_data = pd.read_csv("insurance.csv")

## 1. Groupby

In [4]:
insurance_data.describe(include="all")

,age,sex,bmi,children,smoker,region,charges
count,1338.000000,1338,1338.000000,1338.000000,1338,1338,1338.000000
unique,NaN,2,NaN,NaN,2,4,NaN
top,NaN,male,NaN,NaN,no,southeast,NaN
freq,NaN,676,NaN,NaN,1064,364,NaN
mean,39.207025,NaN,30.663397,1.094918,NaN,NaN,13270.422265
std,14.049960,NaN,6.098187,1.205493,NaN,NaN,12110.011237
min,18.000000,NaN,15.960000,0.000000,NaN,NaN,1121.873900
25%,27.000000,NaN,26.296250,0.000000,NaN,NaN,4740.287150
50%,39.000000,NaN,30.400000,1.000000,NaN,NaN,9382.033000
75%,51.000000,NaN,34.693750,2.000000,NaN,NaN,16639.912515
max,64.000000,NaN,53.130000,5.000000,NaN,NaN,63770.428010

#### 1.2 Pull up the average insurance charge based on region

In [6]:
insurance_data.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

#### 1.3 Pull up the average insurance charges based on region and sex

 ##### Discrete and contiouns data
  * Discrete - Just countable/ Can't segemented
  * Contious - Measurable/Have units /can also segemented

In [15]:
insurance_data.groupby(by=["region","sex"])["charges"].mean().round(2).sort_values()

region     sex
southwest  female    11274.41
northwest  male      12354.12
           female    12479.87
northeast  female    12953.20
southwest  male      13412.88
southeast  female    13499.67
northeast  male      13854.01
southeast  male      15879.62
Name: charges, dtype: float64

### 2. Pivot Table
##### #Presentable comparing 2 categorical features vs 1 contious data

In [17]:
#Pivot Table
pd.pivot_table(data =insurance_data,values = "charges",index="region",columns=["sex"]).round()

sex         female     male
region
northeast  12953.0  13854.0
northwest  12480.0  12354.0
southeast  13500.0  15880.0
southwest  11274.0  13413.0

In [11]:
pd.pivot_table(data =insurance_data,values = "charges",index="region",columns=["sex","children"]).round()
#Presentable comparing 2 categorical features vs 1 contious data

sex         female                                                  male  \
children         0        1        2        3        4        5        0
region
northeast   9790.0  17125.0  14523.0  13730.0  14542.0      NaN  13390.0
northwest  12584.0  11119.0  13128.0  13431.0  11024.0   8966.0   9813.0
southeast  14862.0   9870.0  11766.0  19723.0  18267.0   9924.0  13792.0
southwest  10150.0  10842.0  16230.0   8439.0  10946.0  10024.0  13727.0

sex
children         1        2        3        4        5
region
northeast  15474.0  12318.0  14935.0  14442.0   6979.0
northwest   9515.0  13763.0  22971.0  11508.0      NaN
southeast  17425.0  18648.0  17102.0   8727.0  10307.0
southwest   9971.0  18876.0  12072.0  17924.0   6865.0

### 3. Aggregate

#### 3.1 Find out the average, max, min, sum of charges basedon region

In [21]:
insurance_data.groupby(by="region")["charges"].aggregate(func = ["min","max","mean","sum"]).round(2)

               min       max      mean         sum
region
northeast  1694.80  58571.07  13406.38  4343668.58
northwest  1621.34  60021.40  12417.58  4035712.00
southeast  1121.87  63770.43  14735.41  5363689.76
southwest  1241.56  52590.83  12346.94  4012754.65

### 4. Cross Tab

#### 4.1 how many smokers and non-smokers based on region

In [26]:
#To compute 2 categorical features we use the crosstab
# To find total frequencies between two categorical data
pd.crosstab(index = insurance_data["region"],columns = insurance_data["smoker"],margins=True)

smoker       no  yes   All
region
northeast   257   67   324
northwest   267   58   325
southeast   273   91   364
southwest   267   58   325
All        1064  274  1338

### 5. Concat

In [27]:
insurance_data.age

0       19
1       18
2       28
3       33
4       32
        ..
1333    50
1334    18
1335    18
1336    21
1337    61
Name: age, Length: 1338, dtype: int64

### 6. Apply

#### 6.1 Add new column eligible_criteria based on age

In [7]:
def get_age(x):
    if x > 20:
        return "Eligble"
    else:
        return "Not Eligible"
    

insurance_data["Eligible_Criteria"] = insurance_data["age"].apply(get_age)

insurance_data

,age,sex,bmi,children,smoker,region,charges,Eligible_Criteria
0,19,female,27.900,0,yes,southwest,16884.92400,Not Eligible
1,18,male,33.770,1,no,southeast,1725.55230,Not Eligible
2,28,male,33.000,3,no,southeast,4449.46200,Eligble
3,33,male,22.705,0,no,northwest,21984.47061,Eligble
4,32,male,28.880,0,no,northwest,3866.85520,Eligble
...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Eligble
1334,18,female,31.920,0,no,northeast,2205.98080,Not Eligible
1335,18,female,36.850,0,no,southeast,1629.83350,Not Eligible
1336,21,female,25.800,0,no,southwest,2007.94500,Eligble
1337,61,female,29.070,0,yes,northwest,29141.36030,Eligble

### 7. Lambda

In [8]:
insurance_data["Eligible_Criteria"] = insurance_data["age"].apply(lambda x:1 if x > 20 else 0)

insurance_data

,age,sex,bmi,children,smoker,region,charges,Eligible_Criteria
0,19,female,27.900,0,yes,southwest,16884.92400,0
1,18,male,33.770,1,no,southeast,1725.55230,0
2,28,male,33.000,3,no,southeast,4449.46200,1
3,33,male,22.705,0,no,northwest,21984.47061,1
4,32,male,28.880,0,no,northwest,3866.85520,1
...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,1
1334,18,female,31.920,0,no,northeast,2205.98080,0
1335,18,female,36.850,0,no,southeast,1629.83350,0
1336,21,female,25.800,0,no,southwest,2007.94500,1
1337,61,female,29.070,0,yes,northwest,29141.36030,1