# Chapter 4 - Pandas crash course
## Task
1. Find out the top 5 selling items individual revenu it made 
2. Total revenue of the 5 item sold
3. Find atlease two question on the same dataset

In [2]:
import pandas as pd

In [3]:
#import tsv file
order_data = pd.read_csv("order_data.txt",sep="\t")
order_data

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [14]:
#to find how many null values in each parameter
order_data.isnull().sum()

order_id                 0
quantity                 0
item_name                0
choice_description    1246
item_price               0
dtype: int64

In [15]:
#Whichever column is numerical values, find mean, min and max
order_data.describe()

          order_id     quantity
count  4622.000000  4622.000000
mean    927.254868     1.075725
std     528.890796     0.410186
min       1.000000     1.000000
25%     477.250000     1.000000
50%     926.000000     1.000000
75%    1393.000000     1.000000
max    1834.000000    15.000000

In [17]:
#to fidn data types of each param
order_data.dtypes

order_id               int64
quantity               int64
item_name             object
choice_description    object
item_price            object
dtype: object

In [18]:
#To find no.of item that sold in the order
order_data.nunique()

order_id              1834
quantity                 9
item_name               50
choice_description    1043
item_price              78
dtype: int64

In [7]:
#to Acces to unique item name
order_data["item_name"].unique

<bound method Series.unique of 0                Chips and Fresh Tomato Salsa
1                                        Izze
2                            Nantucket Nectar
3       Chips and Tomatillo-Green Chili Salsa
4                                Chicken Bowl
                        ...
4617                            Steak Burrito
4618                            Steak Burrito
4619                       Chicken Salad Bowl
4620                       Chicken Salad Bowl
4621                       Chicken Salad Bowl
Name: item_name, Length: 4622, dtype: object>

In [35]:
#To find to 5 selling items
order_data.groupby(by="item_name")["quantity"].sum().sort_values(ascending=False).head()

item_name
Chicken Bowl           761
Chicken Burrito        591
Chips and Guacamole    506
Steak Burrito          386
Canned Soft Drink      351
Name: quantity, dtype: int64

In [58]:
#As the price is not numeric since it contains $, let's convert to numerical

#order_data["item_price"]=order_data["item_price"].str.replace("$","").astype(float)
order_data.dtypes

order_id                int64
quantity                int64
item_name              object
choice_description     object
item_price            float64
dtype: object

## 1. Find out the top 5 selling items individual revenu it made

In [60]:
order_data.groupby(by="item_name")["item_price"].sum().sort_values(ascending=False).head()

item_name
Chicken Bowl           7342.73
Chicken Burrito        5575.82
Steak Burrito          3851.43
Steak Bowl             2260.19
Chips and Guacamole    2201.04
Name: item_price, dtype: float64

## 2. Total revenue of the 5 item sold

In [61]:
order_data.groupby(by="item_name")["item_price"].sum().sort_values(ascending=False).head().sum()

np.float64(21231.21)

## 3. find which items have sold more than 100 quantities, you need to group by

In [71]:
qty = order_data.groupby(by="item_name")["quantity"].sum()
qty.loc[qty>100]

item_name
Bottled Water                   211
Canned Soda                     126
Canned Soft Drink               351
Chicken Bowl                    761
Chicken Burrito                 591
Chicken Salad Bowl              123
Chicken Soft Tacos              120
Chips                           230
Chips and Fresh Tomato Salsa    130
Chips and Guacamole             506
Side of Chips                   110
Steak Bowl                      221
Steak Burrito                   386
Name: quantity, dtype: int64

In [83]:
## 4. Find the each item price
#order_data.groupby("item_name")["item_price"].first()
result= order_data["item_price"].sum() / order_data["quantity"].sum()
print(result)

6.938889782783589

In [8]:
order_data["item_name"]

0                Chips and Fresh Tomato Salsa
1                                        Izze
2                            Nantucket Nectar
3       Chips and Tomatillo-Green Chili Salsa
4                                Chicken Bowl
                        ...
4617                            Steak Burrito
4618                            Steak Burrito
4619                       Chicken Salad Bowl
4620                       Chicken Salad Bowl
4621                       Chicken Salad Bowl
Name: item_name, Length: 4622, dtype: object

In [11]:
#To dispaly in a dataframe add extra square bracket
order_data[["item_name","quantity"]]

                                  item_name  quantity
0              Chips and Fresh Tomato Salsa         1
1                                      Izze         1
2                          Nantucket Nectar         1
3     Chips and Tomatillo-Green Chili Salsa         1
4                              Chicken Bowl         2
...                                     ...       ...
4617                          Steak Burrito         1
4618                          Steak Burrito         1
4619                     Chicken Salad Bowl         1
4620                     Chicken Salad Bowl         1
4621                     Chicken Salad Bowl         1

[4622 rows x 2 columns]

In [4]:
#Sort
order_data.sort_values(by="item_name")

,order_id,quantity,item_name,choice_description,item_price
3389,1360,2,6 Pack Soft Drink,[Diet Coke],$12.98
341,148,1,6 Pack Soft Drink,[Diet Coke],$6.49
1849,749,1,6 Pack Soft Drink,[Coke],$6.49
1860,754,1,6 Pack Soft Drink,[Diet Coke],$6.49
2713,1076,1,6 Pack Soft Drink,[Coke],$6.49
...,...,...,...,...,...
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75
781,322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",$8.75
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",$8.49
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",$8.49